[tool.poetry]
name = "Predict-app"
version = "0.1.0"
description = "For predict score"
authors = ["Ramin"]

[tool.poetry.dependencies]
python = "^3.9"
flask = "^2.0.0"
fastapi = "^0.95.0"
requests = "^2.28.0"
line-bot-sdk = "^2.2.1"
gunicorn = "^20.1.0"
